# Generated by Django 5.1.7 on 2025-03-18 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '__first__'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=20, unique=True, verbose_name='반품번호')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='반품일시')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='고객명')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='고객 연락처')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인됨'), ('rejected', '거부됨'), ('completed', '완료됨')], default='pending', max_length=10, verbose_name='상태')),
                ('refund_method', models.CharField(choices=[('cash', '현금'), ('card', '카드'), ('account', '계좌이체'), ('point', '포인트'), ('exchange', '교환'), ('none', '환불 없음')], default='card', max_length=10, verbose_name='환불 방식')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='총 환불 금액')),
                ('reason', models.TextField(verbose_name='반품 사유')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_returns', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_returns', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale', verbose_name='원판매')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.store', verbose_name='반품 매장')),
            ],
            options={
                'verbose_name': '반품',
                'verbose_name_plural': '반품 내역',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='판매 가격')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='환불 금액')),
                ('return_reason', models.CharField(choices=[('defect', '상품 결함'), ('wrong_item', '잘못된 상품'), ('not_as_described', '설명과 다름'), ('customer_request', '고객 요청'), ('expired', '유통기한 만료'), ('damaged', '배송 중 손상'), ('other', '기타')], max_length=20, verbose_name='반품 사유')),
                ('condition', models.CharField(choices=[('new', '미개봉'), ('opened', '개봉됨'), ('used', '사용됨'), ('damaged', '훼손됨')], default='new', max_length=10, verbose_name='상품 상태')),
                ('restock', models.BooleanField(default=True, verbose_name='재입고 여부')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='상품')),
                ('return_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnitems', to='returns.return', verbose_name='반품')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saleitem', verbose_name='판매 항목')),
            ],
            options={
                'verbose_name': '반품 상품',
                'verbose_name_plural': '반품 상품 내역',
            },
        ),
    ]
