# Generated by Django 5.1.7 on 2025-03-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
        ('sales', '0002_sale_sales_channel_alter_saleitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.saleitem', verbose_name='판매 항목'),
        ),
    ]
