# Generated by Django 5.1.7 on 2025-03-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_store_product_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='옵션명')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='표시순서')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='inventory.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품옵션',
                'verbose_name_plural': '상품옵션',
                'ordering': ['display_order', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='옵션값')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='가격조정')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='표시순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성상태')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.productoption', verbose_name='옵션')),
            ],
            options={
                'verbose_name': '옵션값',
                'verbose_name_plural': '옵션값',
                'ordering': ['display_order', 'value'],
                'unique_together': {('option', 'value')},
            },
        ),
    ]
