# Generated by Django 5.1.7 on 2025-03-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productoption_productoptionvalue'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_channel',
            field=models.CharField(choices=[('offline', '오프라인'), ('online', '온라인'), ('other', '기타')], default='offline', max_length=10, verbose_name='판매 채널'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.product', verbose_name='상품'),
        ),
    ]
